Keyboard Shortcuts
showSettingsMenu : Ctrl-,
goToNextError : Alt-E|F8|Alt-F8
goToPreviousError : Alt-Shift-E|Shift-F8|Alt-Shift-F8
selectall : Ctrl-A
gotoline : Ctrl-L|Ctrl-G
fold : Alt-L|Ctrl-F1
unfold : Alt-Shift-L|Ctrl-Shift-F1
toggleFoldWidget : F2|Ctrl-Shift-[|Ctrl-Shift-]
toggleParentFoldWidget : Alt-F2
foldOther : Alt-0|Ctrl-K ctrl-1
unfoldall : Alt-Shift-0|Ctrl-K ctrl-J
findnext : Ctrl-K|F3
findprevious : Ctrl-Shift-K|Shift-F3
selectOrFindNext : Alt-K|Ctrl-K ctrl-D
selectOrFindPrevious : Alt-Shift-K
find : Ctrl-F
overwrite : Insert
selecttostart : Ctrl-Shift-Home
gotostart : Ctrl-Home
selectup : Shift-Up|Shift-Up|Ctrl-Shift-Up
golineup : Up
selecttoend : Ctrl-Shift-End
gotoend : Ctrl-End
selectdown : Shift-Down|Shift-Down|Ctrl-Shift-Down
golinedown : Down
selectwordleft : Ctrl-Shift-Left
gotowordleft : Ctrl-Left
selecttolinestart : Alt-Shift-Left
gotolinestart : Alt-Left|Home
selectleft : Shift-Left
gotoleft : Left
selectwordright : Ctrl-Shift-Right
gotowordright : Ctrl-Right
selecttolineend : Alt-Shift-Right
gotolineend : Alt-Right|End
selectright : Shift-Right
gotoright : Right
selectpagedown : Shift-Pagedown
gotopagedown : Pagedown
selectpageup : Shift-Pageup
gotopageup : Pageup
scrollup : Ctrl-Up
scrolldown : Ctrl-Down
selectlinestart : Shift-Home
selectlineend : Shift-End
togglerecording : Ctrl-Alt-E
replaymacro : Ctrl-Shift-E
jumptomatching : Ctrl-\|Ctrl-P|Ctrl-Shift-\
selecttomatching : Ctrl-Shift-\|Ctrl-Shift-P
expandToMatching : Ctrl-Shift-M
removeline : Ctrl-D|Ctrl-Shift-K
duplicateSelection : Ctrl-Shift-D
sortlines : Ctrl-Alt-S
saveState : Ctrl-Alt-S
togglecomment : Ctrl-/
toggleBlockComment : Ctrl-Shift-/|Alt-Shift-A
modifyNumberUp : Ctrl-Shift-Up
modifyNumberDown : Ctrl-Shift-Down
replace : Ctrl-H
undo : Ctrl-Z
redo : Ctrl-Shift-Z|Ctrl-Y
copylinesup : Alt-Shift-Up|Alt-Shift-Up
movelinesup : Alt-Up
copylinesdown : Alt-Shift-Down|Alt-Shift-Down
movelinesdown : Alt-Down
del : Delete
backspace : Shift-Backspace|Backspace
cut_or_delete : Shift-Delete
removetolinestart : Alt-Backspace
removetolineend : Alt-Delete
removetolinestarthard : Ctrl-Shift-Backspace
removetolineendhard : Ctrl-Shift-Delete
removewordleft : Ctrl-Backspace
removewordright : Ctrl-Delete
outdent : Shift-Tab
indent : Tab
expandSnippet : Tab
blockoutdent : Ctrl-[|Ctrl-[
blockindent : Ctrl-]|Ctrl-]
transposeletters : Alt-Shift-X
touppercase : Ctrl-U
tolowercase : Ctrl-Shift-U
expandtoline : Ctrl-Shift-L|Ctrl-L
openlink : Ctrl-F3
openCommandPallete : F1|Ctrl-Shift-P|F1
addCursorAbove : Ctrl-Alt-Up
addCursorBelow : Ctrl-Alt-Down
addCursorAboveSkipCurrent : Ctrl-Alt-Shift-Up
addCursorBelowSkipCurrent : Ctrl-Alt-Shift-Down
selectMoreBefore : Ctrl-Alt-Left
selectMoreAfter : Ctrl-Alt-Right|Ctrl-D
selectNextBefore : Ctrl-Alt-Shift-Left
selectNextAfter : Ctrl-Alt-Shift-Right
toggleSplitSelectionIntoLines : Ctrl-Alt-L
alignCursors : Ctrl-Alt-A
findAll : Ctrl-Alt-K|Ctrl-Shift-L|Ctrl-F2
submit : Ctrl-Return
editSnippets : Ctrl-Alt-M
editKeyBindings : Ctrl-Alt-B
exitSession : Esc
abandonSession : Ctrl-Alt-Esc
showKeyboardShortcuts : Ctrl-Alt-H|Ctrl-K ctrl-R|Ctrl-K ctrl-S
addLineAfter : Shift-Return
addLineBefore : Ctrl-Shift-Return
pagedown : Alt-Pagedown
pageup : Alt-Pageup
toggleWordWrap : Alt-Z
chainKeys : Ctrl-K
selectAllMatches : Alt-Return
splitSelectionIntoLines : Alt-Shift-I
modeSelect : Ctrl-K input-M
foldall : Ctrl-K ctrl-0
navigateToLastEditLocation : Ctrl-K ctrl-Q
trimTrailingSpace : Ctrl-K ctrl-X
replaceAll : Ctrl-Alt-Return
replaceOne : Ctrl-Shift-1
toggleFindCaseSensitive : Alt-C
toggleFindInSelection : Alt-L
toggleFindRegex : Alt-R
toggleFindWholeWord : Alt-W
removeSecondaryCursors : Shift-Esc
